// Word list for cryptarithmetic puzzles
// Words grouped by length for efficient lookup

export const WORDS_BY_LENGTH: Record<number, string[]> = {
  2: [
    'AD', 'AM', 'AN', 'AS', 'AT', 'AX', 'BE', 'BY', 'DO', 'GO',
    'HE', 'HI', 'IF', 'IN', 'IS', 'IT', 'ME', 'MY', 'NO', 'OF',
    'ON', 'OR', 'SO', 'TO', 'UP', 'US', 'WE'
  ],
  3: [
    'ACE', 'ACT', 'ADD', 'AGE', 'AID', 'AIM', 'AIR', 'ALL', 'AND', 'ANT',
    'ANY', 'APE', 'ARC', 'ARE', 'ARK', 'ARM', 'ART', 'ATE', 'AWE', 'AXE',
    'BAD', 'BAG', 'BAN', 'BAR', 'BAT', 'BED', 'BEE', 'BET', 'BIG', 'BIT',
    'BOW', 'BOX', 'BOY', 'BUD', 'BUG', 'BUN', 'BUS', 'BUT', 'BUY', 'CAB',
    'CAN', 'CAP', 'CAR', 'CAT', 'COB', 'COD', 'COG', 'COP', 'COT', 'COW',
    'CRY', 'CUB', 'CUD', 'CUP', 'CUR', 'CUT', 'DAB', 'DAD', 'DAM', 'DAY',
    'DEN', 'DEW', 'DID', 'DIG', 'DIM', 'DIP', 'DOC', 'DOE', 'DOG', 'DOT',
    'DRY', 'DUB', 'DUD', 'DUE', 'DUG', 'DYE', 'EAR', 'EAT', 'EEL', 'EGG',
    'ELF', 'ELK', 'ELM', 'EMU', 'END', 'ERA', 'EVE', 'EWE', 'EYE', 'FAN',
    'FAR', 'FAT', 'FAX', 'FED', 'FEE', 'FEW', 'FIG', 'FIN', 'FIR', 'FIT',
    'FIX', 'FLU', 'FLY', 'FOB', 'FOE', 'FOG', 'FOR', 'FOX', 'FRY', 'FUN',
    'FUR', 'GAB', 'GAG', 'GAP', 'GAS', 'GAY', 'GEL', 'GEM', 'GET', 'GNU',
    'GOB', 'GOD', 'GOT', 'GUM', 'GUN', 'GUT', 'GUY', 'GYM', 'HAD', 'HAM',
    'HAS', 'HAT', 'HAY', 'HEM', 'HEN', 'HER', 'HEW', 'HID', 'HIM', 'HIP',
    'HIS', 'HIT', 'HOB', 'HOG', 'HOP', 'HOT', 'HOW', 'HUB', 'HUE', 'HUG',
    'HUM', 'HUT', 'ICE', 'ICY', 'ILL', 'IMP', 'INK', 'INN', 'ION', 'IRE',
    'IRK', 'ITS', 'IVY', 'JAB', 'JAM', 'JAR', 'JAW', 'JAY', 'JET', 'JIG',
    'JOB', 'JOG', 'JOT', 'JOY', 'JUG', 'JUT', 'KEG', 'KEN', 'KEY', 'KID',
    'KIN', 'KIT', 'LAB', 'LAC', 'LAD', 'LAG', 'LAP', 'LAW', 'LAX', 'LAY',
    'LEA', 'LED', 'LEG', 'LET', 'LID', 'LIE', 'LIP', 'LIT', 'LOG', 'LOT',
    'LOW', 'LUG', 'MAD', 'MAN', 'MAP', 'MAR', 'MAT', 'MAW', 'MAX', 'MAY',
    'MEN', 'MET', 'MIX', 'MOB', 'MOM', 'MOP', 'MOW', 'MUD', 'MUG', 'MUM',
    'NAB', 'NAG', 'NAP', 'NET', 'NEW', 'NIL', 'NIT', 'NOB', 'NOD', 'NOR',
    'NOT', 'NOW', 'NUB', 'NUN', 'NUT', 'OAK', 'OAR', 'OAT', 'ODD', 'ODE',
    'OFF', 'OFT', 'OHM', 'OIL', 'OLD', 'ONE', 'OPT', 'ORB', 'ORE', 'OUR',
    'OUT', 'OWE', 'OWL', 'OWN', 'PAD', 'PAL', 'PAN', 'PAT', 'PAW', 'PAY',
    'PEA', 'PEG', 'PEN', 'PEP', 'PER', 'PET', 'PEW', 'PIE', 'PIG', 'PIN',
    'PIT', 'PLY', 'POD', 'POP', 'POT', 'POW', 'PRY', 'PUB', 'PUG', 'PUN',
    'PUP', 'PUS', 'PUT', 'RAG', 'RAM', 'RAN', 'RAP', 'RAT', 'RAW', 'RAY',
    'RED', 'REF', 'RIB', 'RID', 'RIG', 'RIM', 'RIP', 'ROB', 'ROD', 'ROE',
    'ROT', 'ROW', 'RUB', 'RUG', 'RUM', 'RUN', 'RUT', 'RYE', 'SAC', 'SAD',
    'SAG', 'SAP', 'SAT', 'SAW', 'SAY', 'SEA', 'SET', 'SEW', 'SHE', 'SHY',
    'SIN', 'SIP', 'SIR', 'SIS', 'SIT', 'SIX', 'SKI', 'SKY', 'SLY', 'SOB',
    'SOD', 'SON', 'SOP', 'SOT', 'SOW', 'SOY', 'SPA', 'SPY', 'STY', 'SUB',
    'SUM', 'SUN', 'SUP', 'TAB', 'TAD', 'TAG', 'TAN', 'TAP', 'TAR', 'TAT',
    'TAX', 'TEA', 'TEN', 'THE', 'THY', 'TIC', 'TIE', 'TIN', 'TIP', 'TOE',
    'TON', 'TOO', 'TOP', 'TOT', 'TOW', 'TOY', 'TRY', 'TUB', 'TUG', 'TWO',
    'URN', 'USE', 'VAN', 'VAT', 'VET', 'VIA', 'VIE', 'VOW', 'WAD', 'WAG',
    'WAR', 'WAS', 'WAX', 'WAY', 'WEB', 'WED', 'WET', 'WHO', 'WHY', 'WIG',
    'WIN', 'WIT', 'WOE', 'WOK', 'WON', 'WOO', 'WOW', 'YAK', 'YAM', 'YAP',
    'YAW', 'YEA', 'YES', 'YET', 'YEW', 'YIN', 'YOU', 'ZAP', 'ZEN', 'ZIP',
    'ZIT', 'ZOO'
  ],
  4: [
    'ABLE', 'ACHE', 'ACID', 'AGED', 'AIDE', 'AIDS', 'AIMS', 'ALSO', 'AREA',
    'ARMS', 'ARMY', 'ARTS', 'AUNT', 'AUTO', 'BABY', 'BACK', 'BAKE', 'BALD',
    'BALL', 'BAND', 'BANK', 'BARN', 'BASE', 'BATH', 'BATS', 'BEAM', 'BEAN',
    'BEAR', 'BEAT', 'BEDS', 'BEEF', 'BEEN', 'BEER', 'BELL', 'BELT', 'BEND',
    'BENT', 'BEST', 'BIKE', 'BILL', 'BIND', 'BIRD', 'BITE', 'BLOW', 'BLUE',
    'BOAT', 'BODY', 'BOLD', 'BOLT', 'BOMB', 'BOND', 'BONE', 'BOOK', 'BOOM',
    'BOOT', 'BORE', 'BORN', 'BOSS', 'BOTH', 'BOWL', 'BOYS', 'BULK', 'BUMP',
    'BURN', 'BUSH', 'BUSY', 'BUYS', 'CAFE', 'CAGE', 'CAKE', 'CALF', 'CALL',
    'CALM', 'CAME', 'CAMP', 'CANE', 'CAPE', 'CAPS', 'CARD', 'CARE', 'CARS',
    'CART', 'CASE', 'CASH', 'CAST', 'CATS', 'CAVE', 'CELL', 'CHAT', 'CHEF',
    'CHIN', 'CHIP', 'CHOP', 'CITY', 'CLAN', 'CLAP', 'CLAY', 'CLIP', 'CLUB',
    'CLUE', 'COAL', 'COAT', 'COCA', 'CODE', 'COIN', 'COLD', 'COME', 'COOK',
    'COOL', 'COPE', 'COPY', 'CORD', 'CORE', 'CORK', 'CORN', 'COST', 'COZY',
    'CRAB', 'CREW', 'CROP', 'CUBE', 'CUPS', 'CURB', 'CURE', 'CURL', 'CUTE',
    'DADS', 'DAME', 'DAMP', 'DARE', 'DARK', 'DART', 'DATA', 'DATE', 'DAWN',
    'DAYS', 'DEAD', 'DEAL', 'DEAN', 'DEAR', 'DEBT', 'DECK', 'DEED', 'DEEM',
    'DEEP', 'DEER', 'DEMO', 'DENT', 'DENY', 'DESK', 'DIAL', 'DICE', 'DIED',
    'DIET', 'DIME', 'DINE', 'DIRT', 'DISC', 'DISH', 'DISK', 'DIVE', 'DOCK',
    'DOES', 'DOGS', 'DOLL', 'DOME', 'DONE', 'DOOR', 'DOSE', 'DOTS', 'DOWN',
    'DRAG', 'DRAW', 'DREW', 'DRIP', 'DROP', 'DRUG', 'DRUM', 'DUAL', 'DUCK',
    'DUDE', 'DUES', 'DUKE', 'DULL', 'DUMP', 'DUNE', 'DUNK', 'DUST', 'DUTY',
    'EACH', 'EARN', 'EARS', 'EASE', 'EAST', 'EASY', 'EATS', 'EDGE', 'EDIT',
    'EGGS', 'ELSE', 'EMIT', 'ENDS', 'ENVY', 'EPIC', 'EURO', 'EVEN', 'EVER',
    'EVIL', 'EXAM', 'EXIT', 'EYES', 'FACE', 'FACT', 'FADE', 'FAIL', 'FAIR',
    'FAKE', 'FALL', 'FAME', 'FANS', 'FARE', 'FARM', 'FAST', 'FATE', 'FEAR',
    'FEAT', 'FEED', 'FEEL', 'FEES', 'FEET', 'FELL', 'FELT', 'FILE', 'FILL',
    'FILM', 'FIND', 'FINE', 'FIRE', 'FIRM', 'FISH', 'FIST', 'FITS', 'FIVE',
    'FLAG', 'FLAME', 'FLAP', 'FLAT', 'FLAW', 'FLED', 'FLEW', 'FLIP', 'FLOW',
    'FOAM', 'FOLD', 'FOLK', 'FOND', 'FONT', 'FOOD', 'FOOL', 'FOOT', 'FORD',
    'FORE', 'FORK', 'FORM', 'FORT', 'FOUL', 'FOUR', 'FOWL', 'FREE', 'FROM',
    'FUEL', 'FULL', 'FUND', 'FUSE', 'FUSS', 'GAIN', 'GAME', 'GANG', 'GAPS',
    'GATE', 'GAVE', 'GAZE', 'GEAR', 'GENE', 'GETS', 'GIFT', 'GILT', 'GIRL',
    'GIST', 'GIVE', 'GLAD', 'GLOW', 'GLUE', 'GOAL', 'GOAT', 'GODS', 'GOES',
    'GOLD', 'GOLF', 'GONE', 'GOOD', 'GOWN', 'GRAB', 'GRAM', 'GRAY', 'GREW',
    'GREY', 'GRID', 'GRIM', 'GRIN', 'GRIP', 'GROW', 'GULF', 'GUNS', 'GUST',
    'GUYS', 'HACK', 'HAIL', 'HAIR', 'HALF', 'HALL', 'HALT', 'HAND', 'HANG',
    'HARD', 'HARM', 'HATE', 'HATS', 'HAUL', 'HAVE', 'HAWK', 'HEAD', 'HEAL',
    'HEAP', 'HEAR', 'HEAT', 'HEEL', 'HELD', 'HELL', 'HELP', 'HEMP', 'HENS',
    'HERB', 'HERD', 'HERE', 'HERO', 'HIDE', 'HIGH', 'HIKE', 'HILL', 'HINT',
    'HIRE', 'HITS', 'HOLD', 'HOLE', 'HOLY', 'HOME', 'HOOD', 'HOOK', 'HOPE',
    'HORN', 'HOST', 'HOUR', 'HUGE', 'HULL', 'HUNG', 'HUNT', 'HURT', 'ICON',
    'IDEA', 'IDLE', 'INCH', 'INTO', 'IRON', 'ISLE', 'ITEM', 'JACK', 'JADE',
    'JAIL', 'JANE', 'JARS', 'JAVA', 'JAZZ', 'JEAN', 'JEEP', 'JERK', 'JETS',
    'JOBS', 'JOHN', 'JOIN', 'JOKE', 'JOLT', 'JOSE', 'JULY', 'JUMP', 'JUNE',
    'JUNK', 'JURY', 'JUST', 'KEEN', 'KEEP', 'KEPT', 'KICK', 'KIDS', 'KILL',
    'KIND', 'KING', 'KISS', 'KITE', 'KNEE', 'KNEW', 'KNIT', 'KNOB', 'KNOT',
    'KNOW', 'LABS', 'LACK', 'LACE', 'LADY', 'LAID', 'LAKE', 'LAMB', 'LAMP',
    'LAND', 'LANE', 'LAST', 'LATE', 'LAWN', 'LAWS', 'LEAD', 'LEAF', 'LEAN',
    'LEAP', 'LEFT', 'LEGS', 'LEND', 'LENS', 'LESS', 'LIAR', 'LICK', 'LIES',
    'LIFE', 'LIFT', 'LIKE', 'LIMB', 'LIME', 'LINE', 'LINK', 'LION', 'LIPS',
    'LIST', 'LIVE', 'LOAD', 'LOAF', 'LOAN', 'LOCK', 'LOFT', 'LOGO', 'LOGS',
    'LONE', 'LONG', 'LOOK', 'LOOP', 'LORD', 'LOSE', 'LOSS', 'LOST', 'LOTS',
    'LOUD', 'LOVE', 'LUCK', 'LUMP', 'LUNG', 'MADE', 'MAIL', 'MAIN', 'MAKE',
    'MALE', 'MALL', 'MANS', 'MANY', 'MAPS', 'MARK', 'MARS', 'MARY', 'MASK',
    'MASS', 'MATE', 'MATH', 'MAYO', 'MAZE', 'MEAL', 'MEAN', 'MEAT', 'MEET',
    'MELT', 'MEMO', 'MENU', 'MERE', 'MESH', 'MESS', 'MICE', 'MILD', 'MILE',
    'MILK', 'MILL', 'MIND', 'MINE', 'MINT', 'MISS', 'MIST', 'MODE', 'MOLD',
    'MONK', 'MOOD', 'MOON', 'MORE', 'MOSS', 'MOST', 'MOVE', 'MUCH', 'MUST',
    'MYTH', 'NAIL', 'NAME', 'NAVY', 'NEAR', 'NEAT', 'NECK', 'NEED', 'NEST',
    'NEWS', 'NEXT', 'NICE', 'NICK', 'NINE', 'NODE', 'NONE', 'NOON', 'NORM',
    'NOSE', 'NOTE', 'NOUN', 'NUTS', 'ODDS', 'OILS', 'OKAY', 'ONCE', 'ONES',
    'ONLY', 'ONTO', 'OPEN', 'ORAL', 'OVEN', 'OVER', 'OWED', 'OWNS', 'PACE',
    'PACK', 'PACT', 'PAGE', 'PAID', 'PAIN', 'PAIR', 'PALE', 'PALM', 'PANS',
    'PARK', 'PART', 'PASS', 'PAST', 'PATH', 'PEAK', 'PEAS', 'PEEL', 'PEER',
    'PENS', 'PETS', 'PICK', 'PIER', 'PIES', 'PIKE', 'PILE', 'PILL', 'PINE',
    'PINK', 'PINS', 'PIPE', 'PITS', 'PLAN', 'PLAY', 'PLEA', 'PLOT', 'PLOW',
    'PLUG', 'PLUM', 'PLUS', 'PODS', 'POEM', 'POET', 'POLE', 'POLL', 'POLO',
    'POND', 'POOL', 'POOR', 'POPE', 'PORK', 'PORT', 'POSE', 'POST', 'POTS',
    'POUR', 'PRAY', 'PREP', 'PREY', 'PROS', 'PULL', 'PULP', 'PUMP', 'PUNK',
    'PURE', 'PUSH', 'PUTS', 'QUIT', 'QUIZ', 'RACE', 'RACK', 'RAGE', 'RAID',
    'RAIL', 'RAIN', 'RAMP', 'RANG', 'RANK', 'RARE', 'RATE', 'RATS', 'RAVE',
    'RAYS', 'READ', 'REAL', 'REAR', 'REDS', 'REED', 'REEF', 'REEL', 'RENT',
    'REST', 'RICE', 'RICH', 'RIDE', 'RIFT', 'RING', 'RIOT', 'RISE', 'RISK',
    'ROAD', 'ROAM', 'ROCK', 'RODE', 'ROLE', 'ROLL', 'ROOF', 'ROOM', 'ROOT',
    'ROPE', 'ROSE', 'RUDE', 'RUGS', 'RUIN', 'RULE', 'RUNS', 'RUSH', 'RUST',
    'SACK', 'SAFE', 'SAGE', 'SAID', 'SAIL', 'SAKE', 'SALE', 'SALT', 'SAME',
    'SAND', 'SANE', 'SANG', 'SANK', 'SAVE', 'SAYS', 'SCAN', 'SEAL', 'SEAM',
    'SEAS', 'SEAT', 'SECT', 'SEED', 'SEEK', 'SEEM', 'SEEN', 'SELF', 'SELL',
    'SEND', 'SENT', 'SEPT', 'SETS', 'SHED', 'SHIP', 'SHOP', 'SHOT', 'SHOW',
    'SHUT', 'SICK', 'SIDE', 'SIGH', 'SIGN', 'SILK', 'SING', 'SINK', 'SITE',
    'SIZE', 'SKIM', 'SKIN', 'SKIP', 'SKIS', 'SLAB', 'SLAM', 'SLAP', 'SLID',
    'SLIM', 'SLIP', 'SLOT', 'SLOW', 'SNAP', 'SNOW', 'SOAK', 'SOAP', 'SOCK',
    'SODA', 'SOFA', 'SOFT', 'SOIL', 'SOLD', 'SOLE', 'SOME', 'SONG', 'SONS',
    'SOON', 'SORE', 'SORT', 'SOUL', 'SOUP', 'SOUR', 'SPAN', 'SPIN', 'SPIT',
    'SPOT', 'SPUN', 'STAB', 'STAR', 'STAY', 'STEM', 'STEP', 'STEW', 'STIR',
    'STOP', 'STOR', 'STUD', 'SUCH', 'SUIT', 'SUNG', 'SUNK', 'SURE', 'SURF',
    'SWAM', 'SWAN', 'SWAP', 'SWIM', 'TABS', 'TACK', 'TAIL', 'TAKE', 'TALE',
    'TALK', 'TALL', 'TAME', 'TANK', 'TAPE', 'TAPS', 'TASK', 'TAXI', 'TEAM',
    'TEAR', 'TECH', 'TEEN', 'TELL', 'TEND', 'TENS', 'TENT', 'TERM', 'TEST',
    'TEXT', 'THAN', 'THAT', 'THEM', 'THEN', 'THEY', 'THIN', 'THIS', 'THUS',
    'TICK', 'TIDE', 'TIDY', 'TIED', 'TIER', 'TIES', 'TILE', 'TILL', 'TILT',
    'TIME', 'TINT', 'TINY', 'TIPS', 'TIRE', 'TOES', 'TOLD', 'TOLL', 'TOMB',
    'TONE', 'TONS', 'TONY', 'TOOK', 'TOOL', 'TOPS', 'TORE', 'TORN', 'TOSS',
    'TOUR', 'TOWN', 'TOYS', 'TRAP', 'TRAY', 'TREE', 'TREK', 'TRIM', 'TRIO',
    'TRIP', 'TROT', 'TRUE', 'TUBE', 'TUBS', 'TUCK', 'TUNE', 'TURN', 'TWIN',
    'TYPE', 'UGLY', 'UNIT', 'UPON', 'URGE', 'USED', 'USER', 'USES', 'VAIN',
    'VARY', 'VASE', 'VAST', 'VEIL', 'VEIN', 'VERB', 'VERY', 'VEST', 'VIEW',
    'VINE', 'VISA', 'VOID', 'VOLT', 'VOTE', 'WADE', 'WAGE', 'WAIT', 'WAKE',
    'WALK', 'WALL', 'WAND', 'WANT', 'WARD', 'WARM', 'WARN', 'WARP', 'WARS',
    'WASH', 'WASP', 'WAVE', 'WAYS', 'WEAK', 'WEAR', 'WEED', 'WEEK', 'WELL',
    'WENT', 'WERE', 'WEST', 'WHAT', 'WHEN', 'WHIP', 'WHOM', 'WIDE', 'WIFE',
    'WILD', 'WILL', 'WIND', 'WINE', 'WING', 'WINS', 'WIPE', 'WIRE', 'WISE',
    'WISH', 'WITH', 'WOKE', 'WOLF', 'WOMB', 'WONT', 'WOOD', 'WOOL', 'WORD',
    'WORE', 'WORK', 'WORM', 'WORN', 'WRAP', 'YARD', 'YARN', 'YEAR', 'YELL',
    'YOUR', 'ZERO', 'ZEST', 'ZINC', 'ZONE', 'ZOOM'
  ],
  5: [
    'ABOUT', 'ABOVE', 'ABUSE', 'ACTED', 'ACTOR', 'ACUTE', 'ADDED', 'ADMIT',
    'ADOPT', 'ADULT', 'AFTER', 'AGAIN', 'AGENT', 'AGREE', 'AHEAD', 'ALARM',
    'ALBUM', 'ALERT', 'ALIEN', 'ALIGN', 'ALIKE', 'ALIVE', 'ALLOW', 'ALLOY',
    'ALONE', 'ALONG', 'ALTER', 'AMONG', 'ANGEL', 'ANGER', 'ANGLE', 'ANGRY',
    'ANIME', 'ANKLE', 'APART', 'APPLE', 'APPLY', 'ARENA', 'ARGUE', 'ARISE',
    'ARMOR', 'ARRAY', 'ARROW', 'ASIDE', 'ASSET', 'ATLAS', 'AUDIO', 'AUDIT',
    'AUNTS', 'AVOID', 'AWAKE', 'AWARD', 'AWARE', 'AWFUL', 'BACON', 'BADGE',
    'BADLY', 'BAGEL', 'BAKER', 'BALLS', 'BANDS', 'BANKS', 'BASED', 'BASES',
    'BASIC', 'BASIN', 'BASIS', 'BATCH', 'BEACH', 'BEADS', 'BEANS', 'BEARD',
    'BEARS', 'BEAST', 'BEATS', 'BEGUN', 'BEING', 'BELLS', 'BELOW', 'BELTS',
    'BENCH', 'BERRY', 'BILLS', 'BIRDS', 'BIRTH', 'BLACK', 'BLADE', 'BLAME',
    'BLANK', 'BLAST', 'BLAZE', 'BLEND', 'BLESS', 'BLIND', 'BLOCK', 'BLOGS',
    'BLOND', 'BLOOD', 'BLOWN', 'BLUES', 'BLUNT', 'BOARD', 'BOATS', 'BONDS',
    'BONES', 'BONUS', 'BOOKS', 'BOOST', 'BOOTS', 'BORED', 'BOUND', 'BOXES',
    'BRAIN', 'BRAKE', 'BRAND', 'BRASS', 'BRAVE', 'BREAD', 'BREAK', 'BREED',
    'BRICK', 'BRIDE', 'BRIEF', 'BRING', 'BROAD', 'BROKE', 'BROOK', 'BROWN',
    'BRUSH', 'BUILD', 'BUILT', 'BULLS', 'BUNCH', 'BURNS', 'BURST', 'BUSES',
    'BUYER', 'CABIN', 'CABLE', 'CAKES', 'CALLS', 'CAMEL', 'CAMPS', 'CANAL',
    'CANDY', 'CARDS', 'CARGO', 'CARRY', 'CASES', 'CATCH', 'CAUSE', 'CEASE',
    'CELLS', 'CHAIN', 'CHAIR', 'CHALK', 'CHAMP', 'CHAOS', 'CHARM', 'CHART',
    'CHASE', 'CHEAP', 'CHEAT', 'CHECK', 'CHEEK', 'CHEER', 'CHESS', 'CHEST',
    'CHICK', 'CHIEF', 'CHILD', 'CHILL', 'CHINA', 'CHIPS', 'CHORD', 'CHOSE',
    'CHUNK', 'CIDER', 'CIGAR', 'CITED', 'CIVIC', 'CIVIL', 'CLAIM', 'CLASS',
    'CLEAN', 'CLEAR', 'CLERK', 'CLICK', 'CLIFF', 'CLIMB', 'CLOCK', 'CLONE',
    'CLOSE', 'CLOTH', 'CLOUD', 'CLUBS', 'CLUES', 'COACH', 'COAST', 'COATS',
    'COCOA', 'CODES', 'COINS', 'COLON', 'COLOR', 'COMES', 'COMIC', 'CORAL',
    'CORPS', 'COUCH', 'COUGH', 'COULD', 'COUNT', 'COURT', 'COVER', 'CRACK',
    'CRAFT', 'CRANE', 'CRASH', 'CRAZY', 'CREAM', 'CREEK', 'CREEP', 'CREST',
    'CRIES', 'CRIME', 'CRISP', 'CROPS', 'CROSS', 'CROWD', 'CROWN', 'CRUDE',
    'CRUEL', 'CRUSH', 'CUBIC', 'CURRY', 'CURSE', 'CURVE', 'CYCLE', 'DAILY',
    'DAIRY', 'DANCE', 'DATED', 'DATES', 'DEALT', 'DEATH', 'DEBUT', 'DECKS',
    'DELAY', 'DELTA', 'DENSE', 'DEPOT', 'DEPTH', 'DERBY', 'DESKS', 'DEVIL',
    'DIARY', 'DIGIT', 'DIRTY', 'DISCO', 'DISKS', 'DITCH', 'DIVER', 'DODGE',
    'DOING', 'DOLLS', 'DONOR', 'DOORS', 'DOUBT', 'DOUGH', 'DRAFT', 'DRAIN',
    'DRAMA', 'DRANK', 'DRAWN', 'DRAWS', 'DREAD', 'DREAM', 'DRESS', 'DRIED',
    'DRIFT', 'DRILL', 'DRINK', 'DRIVE', 'DROIT', 'DROPS', 'DROVE', 'DRUGS',
    'DRUMS', 'DRUNK', 'DUCKS', 'DUDES', 'DUMMY', 'DUMPS', 'DUNES', 'DUSTY',
    'DUTCH', 'DWARF', 'EAGER', 'EAGLE', 'EARLY', 'EARTH', 'EATEN', 'EATER',
    'EBONY', 'EDGES', 'EIGHT', 'ELBOW', 'ELDER', 'ELECT', 'ELITE', 'EMPTY',
    'ENDED', 'ENEMY', 'ENJOY', 'ENTER', 'ENTRY', 'EQUAL', 'EQUIP', 'ERROR',
    'ESSAY', 'ETHIC', 'EUROS', 'EVENT', 'EVERY', 'EXACT', 'EXAMS', 'EXCEL',
    'EXIST', 'EXITS', 'EXTRA', 'FACED', 'FACES', 'FACTS', 'FAINT', 'FAIRY',
    'FAITH', 'FALSE', 'FAMED', 'FANCY', 'FARMS', 'FATAL', 'FATTY', 'FAULT',
    'FAVOR', 'FEAST', 'FEELS', 'FENCE', 'FERRY', 'FEWER', 'FIBER', 'FIELD',
    'FIFTH', 'FIFTY', 'FIGHT', 'FILED', 'FILES', 'FILMS', 'FINAL', 'FINDS',
    'FINED', 'FINER', 'FIRES', 'FIRMS', 'FIRST', 'FISHY', 'FIXED', 'FLAIR',
    'FLAME', 'FLASH', 'FLATS', 'FLEET', 'FLESH', 'FLIES', 'FLOAT', 'FLOCK',
    'FLOOD', 'FLOOR', 'FLOUR', 'FLOWS', 'FLUID', 'FLUSH', 'FLUTE', 'FOCAL',
    'FOCUS', 'FOLKS', 'FONTS', 'FOODS', 'FOOLS', 'FORCE', 'FORGE', 'FORMS',
    'FORTH', 'FORTY', 'FORUM', 'FOUND', 'FRAME', 'FRANK', 'FRAUD', 'FREAK',
    'FREED', 'FRESH', 'FRIED', 'FRONT', 'FROST', 'FRUIT', 'FUELS', 'FULLY',
    'FUNDS', 'FUNGI', 'FUNNY', 'GAINS', 'GAMMA', 'GASES', 'GATES', 'GAUGE',
    'GEARS', 'GENES', 'GENRE', 'GHOST', 'GIANT', 'GIFTS', 'GIRLS', 'GIVEN',
    'GIVES', 'GLAND', 'GLASS', 'GLOBE', 'GLORY', 'GLOSS', 'GLOVE', 'GOALS',
    'GOATS', 'GOING', 'GONNA', 'GOODS', 'GOOSE', 'GRACE', 'GRADE', 'GRAIN',
    'GRAMS', 'GRAND', 'GRANT', 'GRAPE', 'GRAPH', 'GRASP', 'GRASS', 'GRAVE',
    'GRAVY', 'GREAT', 'GREEN', 'GREET', 'GRIEF', 'GRILL', 'GRIND', 'GRIPS',
    'GROSS', 'GROUP', 'GROVE', 'GROWN', 'GROWS', 'GUARD', 'GUESS', 'GUEST',
    'GUIDE', 'GUILD', 'GUILT', 'GUISE', 'GULCH', 'GUSTY', 'HABIT', 'HAIRS',
    'HALLS', 'HANDS', 'HANDY', 'HANGS', 'HAPPY', 'HARSH', 'HASTE', 'HATCH',
    'HAVEN', 'HEADS', 'HEARD', 'HEART', 'HEAVY', 'HEDGE', 'HEELS', 'HELLO',
    'HELPS', 'HENCE', 'HERBS', 'HERDS', 'HILLS', 'HINTS', 'HIRED', 'HOBBY',
    'HOLDS', 'HOLES', 'HOMES', 'HONEY', 'HONOR', 'HOOKS', 'HOPED', 'HOPES',
    'HORNS', 'HORSE', 'HOSTS', 'HOTEL', 'HOURS', 'HOUSE', 'HUMAN', 'HUMOR',
    'HURRY', 'ICIER', 'ICONS', 'IDEAL', 'IDEAS', 'IMAGE', 'IMPLY', 'INDEX',
    'INDIE', 'INNER', 'INPUT', 'INTEL', 'INTER', 'INTRO', 'IRONS', 'IRONY',
    'ISSUE', 'ITEMS', 'IVORY', 'JEANS', 'JELLY', 'JEWEL', 'JOINS', 'JOINT',
    'JOKER', 'JOKES', 'JOLLY', 'JONES', 'JUDGE', 'JUICE', 'JUICY', 'JUMPS',
    'JUMPY', 'JUNTA', 'KEEPS', 'KICKS', 'KILLS', 'KINDS', 'KINGS', 'KITES',
    'KNACK', 'KNEES', 'KNELT', 'KNIFE', 'KNOCK', 'KNOTS', 'KNOWN', 'KNOWS',
    'LABEL', 'LABOR', 'LACKS', 'LAKES', 'LAMPS', 'LANDS', 'LANES', 'LARGE',
    'LASER', 'LASTS', 'LATER', 'LAUGH', 'LAWNS', 'LAYER', 'LEADS', 'LEAFY',
    'LEARN', 'LEASE', 'LEAST', 'LEAVE', 'LEGAL', 'LEMON', 'LEVEL', 'LEVER',
    'LIGHT', 'LIKED', 'LIKES', 'LIMBS', 'LIMIT', 'LINED', 'LINEN', 'LINER',
    'LINES', 'LINKS', 'LIONS', 'LISTS', 'LITER', 'LIVED', 'LIVER', 'LIVES',
    'LOADS', 'LOANS', 'LOBBY', 'LOCAL', 'LOCKS', 'LODGE', 'LOGIC', 'LOGOS',
    'LOOKS', 'LOOPS', 'LOOSE', 'LORDS', 'LOSER', 'LOSES', 'LOTUS', 'LOVED',
    'LOVER', 'LOVES', 'LOWER', 'LOYAL', 'LUCKY', 'LUMPS', 'LUNCH', 'LUNGS',
    'LYING', 'MAGIC', 'MAILS', 'MAJOR', 'MAKER', 'MAKES', 'MALES', 'MALLS',
    'MANGA', 'MANOR', 'MAPLE', 'MARCH', 'MARKS', 'MARSH', 'MASKS', 'MATCH',
    'MATES', 'MATHS', 'MAYOR', 'MEALS', 'MEANS', 'MEANT', 'MEATS', 'MEDAL',
    'MEDIA', 'MEETS', 'MELON', 'MELTS', 'MENUS', 'MERCY', 'MERGE', 'MERIT',
    'MERRY', 'MESSY', 'METAL', 'METER', 'MICRO', 'MIGHT', 'MILLS', 'MINDS',
    'MINED', 'MINER', 'MINES', 'MINOR', 'MINUS', 'MISTY', 'MIXED', 'MIXER',
    'MODEL', 'MODES', 'MOIST', 'MONEY', 'MONKS', 'MONTH', 'MOODS', 'MOONS',
    'MORAL', 'MOTOR', 'MOULD', 'MOUNT', 'MOUSE', 'MOUTH', 'MOVED', 'MOVER',
    'MOVES', 'MOVIE', 'MUDDY', 'MULTI', 'MUMMY', 'MUSIC', 'MYTHS', 'NAILS',
    'NAIVE', 'NAKED', 'NAMED', 'NAMES', 'NASTY', 'NAVAL', 'NEEDS', 'NERVE',
    'NEVER', 'NEWER', 'NEWLY', 'NIGHT', 'NINJA', 'NINTH', 'NOBLE', 'NODES',
    'NOISE', 'NOISY', 'NORMS', 'NORTH', 'NOTCH', 'NOTED', 'NOTES', 'NOVEL',
    'NURSE', 'OCCUR', 'OCEAN', 'OFTEN', 'OLDER', 'OLIVE', 'ONSET', 'OPENS',
    'OPERA', 'OPTED', 'ORBIT', 'ORDER', 'OTHER', 'OUGHT', 'OUNCE', 'OUTER',
    'OWNED', 'OWNER', 'OXIDE', 'OZONE', 'PACED', 'PACKS', 'PAGES', 'PAINS',
    'PAINT', 'PAIRS', 'PALMS', 'PANEL', 'PANIC', 'PANTS', 'PAPER', 'PARKS',
    'PARTS', 'PARTY', 'PASTA', 'PASTE', 'PATCH', 'PATHS', 'PAUSE', 'PEACE',
    'PEACH', 'PEAKS', 'PEARL', 'PEERS', 'PENNY', 'PERKS', 'PESTS', 'PHASE',
    'PHONE', 'PHOTO', 'PIANO', 'PICKS', 'PIECE', 'PILES', 'PILLS', 'PILOT',
    'PINCH', 'PINTS', 'PIPES', 'PITCH', 'PIXEL', 'PIZZA', 'PLACE', 'PLAIN',
    'PLANE', 'PLANS', 'PLANT', 'PLATE', 'PLAYS', 'PLAZA', 'PLEAS', 'PLOTS',
    'PLUCK', 'PLUGS', 'PLUMB', 'PLUMP', 'POEMS', 'POETS', 'POINT', 'POKER',
    'POLAR', 'POLES', 'POLLS', 'PONDS', 'POOLS', 'PORCH', 'PORES', 'PORTS',
    'POSED', 'POSES', 'POSTS', 'POUCH', 'POUND', 'POWER', 'PRESS', 'PRICE',
    'PRIDE', 'PRIME', 'PRINT', 'PRIOR', 'PRISM', 'PRIZE', 'PROBE', 'PROMO',
    'PRONE', 'PROOF', 'PROPS', 'PROSE', 'PROUD', 'PROVE', 'PROXY', 'PSALM',
    'PULLS', 'PULSE', 'PUMPS', 'PUNCH', 'PUPIL', 'PUPPY', 'PURSE', 'PUSHY',
    'QUEEN', 'QUERY', 'QUEST', 'QUEUE', 'QUICK', 'QUIET', 'QUILT', 'QUITE',
    'QUOTA', 'QUOTE', 'RACES', 'RACKS', 'RADAR', 'RADIO', 'RAIDS', 'RAILS',
    'RAINS', 'RAINY', 'RAISE', 'RALLY', 'RANCH', 'RANGE', 'RANKS', 'RAPID',
    'RATED', 'RATES', 'RATIO', 'REACH', 'REACT', 'READS', 'READY', 'REALM',
    'REBEL', 'REFER', 'REIGN', 'RELAX', 'RELAY', 'RENAL', 'RENEW', 'RENTS',
    'REPLY', 'RESIN', 'RESIT', 'RETRO', 'RIDER', 'RIDES', 'RIDGE', 'RIFLE',
    'RIGHT', 'RIGID', 'RINGS', 'RIOTS', 'RISEN', 'RISES', 'RISKS', 'RISKY',
    'RIVAL', 'RIVER', 'ROADS', 'ROAST', 'ROBOT', 'ROCKS', 'ROCKY', 'ROGUE',
    'ROLES', 'ROLLS', 'ROMAN', 'ROOFS', 'ROOMS', 'ROOTS', 'ROPES', 'ROSES',
    'ROUGH', 'ROUND', 'ROUTE', 'ROYAL', 'RUGBY', 'RUINS', 'RULED', 'RULER',
    'RULES', 'RURAL', 'RUSTY', 'SADLY', 'SAFER', 'SAINT', 'SALAD', 'SALES',
    'SALON', 'SALTS', 'SALTY', 'SAMBA', 'SANDY', 'SAUCE', 'SAVED', 'SAVES',
    'SCALE', 'SCALP', 'SCAMS', 'SCANS', 'SCARE', 'SCARF', 'SCARY', 'SCENE',
    'SCENT', 'SCORE', 'SCOUT', 'SCRAP', 'SEALS', 'SEAMS', 'SEATS', 'SEEDS',
    'SEEKS', 'SEEMS', 'SELLS', 'SENDS', 'SENSE', 'SERVE', 'SETUP', 'SEVEN',
    'SHADE', 'SHADY', 'SHAFT', 'SHAKE', 'SHAKY', 'SHALL', 'SHAME', 'SHAPE',
    'SHARE', 'SHARK', 'SHARP', 'SHEDS', 'SHEER', 'SHEET', 'SHELF', 'SHELL',
    'SHIFT', 'SHINY', 'SHIPS', 'SHIRT', 'SHOCK', 'SHOES', 'SHOOK', 'SHOOT',
    'SHOPS', 'SHORE', 'SHORT', 'SHOTS', 'SHOUT', 'SHOWN', 'SHOWS', 'SHRUG',
    'SIDES', 'SIEGE', 'SIGHT', 'SIGMA', 'SIGNS', 'SILLY', 'SINCE', 'SITES',
    'SIXTH', 'SIXTY', 'SIZED', 'SIZES', 'SKILL', 'SKIRT', 'SKULL', 'SLATE',
    'SLAVE', 'SLEEP', 'SLEPT', 'SLICE', 'SLIDE', 'SLOPE', 'SLOTS', 'SMALL',
    'SMART', 'SMELL', 'SMILE', 'SMITH', 'SMOKE', 'SNACK', 'SNAKE', 'SNAPS',
    'SNEAK', 'SNOWY', 'SOBER', 'SOCKS', 'SOILS', 'SOLAR', 'SOLID', 'SOLVE',
    'SONGS', 'SOONER', 'SORRY', 'SORTS', 'SOULS', 'SOUND', 'SOUTH', 'SPACE',
    'SPARE', 'SPARK', 'SPEAK', 'SPEED', 'SPELL', 'SPEND', 'SPENT', 'SPICE',
    'SPICY', 'SPILL', 'SPINE', 'SPITE', 'SPLIT', 'SPOKE', 'SPOON', 'SPORT',
    'SPOTS', 'SPRAY', 'SQUAD', 'STACK', 'STAFF', 'STAGE', 'STAIN', 'STAIR',
    'STAKE', 'STALE', 'STAMP', 'STAND', 'STARK', 'STARS', 'START', 'STATE',
    'STATS', 'STAYS', 'STEAK', 'STEAL', 'STEAM', 'STEEL', 'STEEP', 'STEER',
    'STEMS', 'STEPS', 'STERN', 'STICK', 'STIFF', 'STILL', 'STOCK', 'STOLE',
    'STONE', 'STONY', 'STOOD', 'STOOL', 'STOPS', 'STORE', 'STORM', 'STORY',
    'STOVE', 'STRAP', 'STRAW', 'STRAY', 'STRIP', 'STUCK', 'STUDY', 'STUFF',
    'STUNT', 'STYLE', 'SUGAR', 'SUITE', 'SUITS', 'SUNNY', 'SUPER', 'SURGE',
    'SWAMP', 'SWEAR', 'SWEAT', 'SWEEP', 'SWEET', 'SWEPT', 'SWIFT', 'SWING',
    'SWISS', 'SWORD', 'SWORE', 'SWORN', 'SWUNG', 'TABLE', 'TAILS', 'TAKEN',
    'TAKES', 'TALES', 'TALKS', 'TANKS', 'TAPES', 'TASTE', 'TASTY', 'TAXES',
    'TEACH', 'TEAMS', 'TEARS', 'TEENS', 'TEETH', 'TELLS', 'TEMPO', 'TENDS',
    'TENSE', 'TENTH', 'TENTS', 'TERMS', 'TESTS', 'TEXTS', 'THANK', 'THEFT',
    'THEME', 'THICK', 'THIEF', 'THIGH', 'THING', 'THINK', 'THIRD', 'THOSE',
    'THREE', 'THREW', 'THROW', 'THUMB', 'TIGER', 'TIGHT', 'TILES', 'TIMER',
    'TIMES', 'TIRED', 'TIRES', 'TITLE', 'TOAST', 'TODAY', 'TOKEN', 'TONES',
    'TOOLS', 'TOOTH', 'TOPIC', 'TORCH', 'TOTAL', 'TOUCH', 'TOUGH', 'TOURS',
    'TOWEL', 'TOWER', 'TOWNS', 'TOXIC', 'TRACE', 'TRACK', 'TRADE', 'TRAIL',
    'TRAIN', 'TRAIT', 'TRAPS', 'TRASH', 'TREAD', 'TREAT', 'TREES', 'TREND',
    'TRIAL', 'TRIBE', 'TRICK', 'TRIED', 'TRIES', 'TRIPS', 'TROOP', 'TROUT',
    'TRUCK', 'TRULY', 'TRUMP', 'TRUNK', 'TRUST', 'TRUTH', 'TUBES', 'TULIP',
    'TUMMY', 'TUMOR', 'TUNED', 'TUNER', 'TUNES', 'TURNS', 'TUTOR', 'TWICE',
    'TWINS', 'TWIST', 'TYPED', 'TYPES', 'ULTRA', 'UNCLE', 'UNDER', 'UNFIT',
    'UNION', 'UNITE', 'UNITS', 'UNITY', 'UNTIL', 'UPPER', 'UPSET', 'URBAN',
    'URGED', 'USAGE', 'USERS', 'USING', 'USUAL', 'VAGUE', 'VALID', 'VALUE',
    'VALVE', 'VAPOR', 'VAULT', 'VEGAS', 'VEINS', 'VENUE', 'VERGE', 'VERSE',
    'VIDEO', 'VIEWS', 'VIGOR', 'VILLA', 'VINES', 'VINYL', 'VIRAL', 'VIRUS',
    'VISIT', 'VITAL', 'VIVID', 'VOCAL', 'VODKA', 'VOICE', 'VOLTS', 'VOTER',
    'VOTES', 'WAGES', 'WAGON', 'WAIST', 'WAITS', 'WALKS', 'WALLS', 'WANDS',
    'WANTS', 'WARNS', 'WASTE', 'WATCH', 'WATER', 'WATTS', 'WAVES', 'WEARS',
    'WEARY', 'WEDGE', 'WEEDS', 'WEEKS', 'WEIGH', 'WEIRD', 'WELLS', 'WHALE',
    'WHEAT', 'WHEEL', 'WHERE', 'WHICH', 'WHILE', 'WHITE', 'WHOLE', 'WHOSE',
    'WICKED', 'WIDER', 'WIDTH', 'WIDOW', 'WINDS', 'WINDY', 'WINES', 'WINGS',
    'WIRED', 'WIRES', 'WITCH', 'WIVES', 'WOKEN', 'WOMAN', 'WOMEN', 'WOODS',
    'WORDS', 'WORKS', 'WORLD', 'WORMS', 'WORRY', 'WORSE', 'WORST', 'WORTH',
    'WOULD', 'WOUND', 'WRATH', 'WRECK', 'WRIST', 'WRITE', 'WRONG', 'WROTE',
    'YACHT', 'YARDS', 'YEARS', 'YEAST', 'YIELD', 'YOUNG', 'YOURS', 'YOUTH',
    'ZEBRA', 'ZEROS', 'ZONES'
  ]
};

// Get all words as a flat array
export function getAllWords(): string[] {
  return Object.values(WORDS_BY_LENGTH).flat();
}

// Get words of a specific length
export function getWordsByLength(length: number): string[] {
  return WORDS_BY_LENGTH[length] || [];
}

// Check if a string is a valid word
export function isValidWord(word: string): boolean {
  const words = WORDS_BY_LENGTH[word.length];
  return words ? words.includes(word.toUpperCase()) : false;
}
